# Generated by Django 5.1.2 on 2024-11-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
    ]
