# Generated by Django 5.1.1 on 2024-11-18 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_pedido_historico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historico',
            new_name='Historic',
        ),
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='historic',
            old_name='pedido',
            new_name='order',
        ),
    ]
