# Generated by Django 4.2.16 on 2024-11-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
        ('pages', '0010_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='superuser.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
