# Generated by Django 4.2.16 on 2024-11-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
