# Generated by Django 4.2.16 on 2024-11-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_delete_discount'),
        ('pages', '0014_order_address_order_carrier_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.userpayments'),
        ),
    ]
