# Generated by Django 4.2.16 on 2024-12-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_alter_discount_discount_type'),
        ('pages', '0015_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.discount'),
        ),
    ]
