# Generated by Django 4.2.16 on 2024-12-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_alter_discount_discount_type'),
        ('pages', '0017_alter_cartitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.discount'),
        ),
    ]
