# Generated by Django 4.2.16 on 2024-11-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(),
        ),
    ]
