# Generated by Django 4.2.16 on 2024-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_alter_discount_end_date_alter_discount_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixo'), ('percentage', 'Percentual')], default='percentage', max_length=10),
        ),
    ]
