# Generated by Django 4.2.16 on 2024-11-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_userpayments_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='payment_type',
            field=models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Debit Card', 'Cartão de Débito')], default='Cartão de Crédito', max_length=50),
        ),
    ]
