# Generated by Django 4.2.16 on 2024-11-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='page',
        ),
    ]
