# Generated by Django 4.2.16 on 2024-11-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
